services:

  ros2:
    build:
      context: ../..
      dockerfile: .docker/arduino_uno_q/Dockerfile

    container_name: turtlebot

    network_mode: host
    ipc: host

    stdin_open: true
    tty: true
    
    volumes:
      - ../../turtle_ws:/turtle_ws
      - ../../test/msgpack_test.py:/test/msgpack_test.py
      - /var/run/arduino-router.sock:/var/run/arduino-router.sock

    environment:
      ROS_DOMAIN_ID: 0

    devices:
      - /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0:/dev/rplidar